name: Rust checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-format-and-lint:
    name: Check & Lint
    runs-on: selfhosted-heavy
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          chmod +x .ci/install-deps.sh && .ci/install-deps.sh
          echo "/opt/cargo_home/bin" >> $GITHUB_PATH
          echo "RUSTUP_HOME=/opt/rustup_home" >> $GITHUB_ENV
          echo "CARGO_HOME=/opt/cargo_home" >> $GITHUB_ENV
          echo "CARGO_TARGET_DIR=/opt/cargo_target" >> $GITHUB_ENV

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Lint with clippy
        run: cargo clippy -- -D warnings

  cargo-check:
    name: Cargo Check
    runs-on: selfhosted-heavy
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          chmod +x .ci/install-deps.sh && .ci/install-deps.sh
          echo "/opt/cargo_home/bin" >> $GITHUB_PATH
          echo "RUSTUP_HOME=/opt/rustup_home" >> $GITHUB_ENV
          echo "CARGO_HOME=/opt/cargo_home" >> $GITHUB_ENV
          echo "CARGO_TARGET_DIR=/opt/cargo_target" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Check
        run: cargo check --all
