name: Rust checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check-format-and-lint:
    name: Check & Lint
    runs-on: k8s-worker-4
    steps:
      - uses: actions/checkout@v4

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Lint with clippy
        run: cargo clippy -- -D warnings

  cargo-check:
    name: Cargo Check
    runs-on: k8s-worker-4
    steps:
      - uses: actions/checkout@v4

      - name: Cargo Check
        run: cargo check --all

  cargo-test:
    name: Cargo Test
    runs-on: k8s-worker-6
    steps:
      - uses: actions/checkout@v4
      - name: Cargo Tests
        env:
          RUST_LOG: info
        run: cargo t --release
