name: Rust checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check-format-and-lint:
    name: Check & Lint
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          chmod +x .ci/install-deps.sh && .ci/install-deps.sh
          echo "/opt/cargo_home/bin" >> $GITHUB_PATH
          echo "RUSTUP_HOME=/opt/rustup_home" >> $GITHUB_ENV
          echo "CARGO_HOME=/opt/cargo_home" >> $GITHUB_ENV
          echo "CARGO_TARGET_DIR=/opt/cargo_target" >> $GITHUB_ENV

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Lint with clippy
        run: cargo clippy -- -D warnings

  cargo-check:
    name: Cargo Check
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          chmod +x .ci/install-deps.sh && .ci/install-deps.sh
          echo "/opt/cargo_home/bin" >> $GITHUB_PATH
          echo "RUSTUP_HOME=/opt/rustup_home" >> $GITHUB_ENV
          echo "CARGO_HOME=/opt/cargo_home" >> $GITHUB_ENV
          echo "CARGO_TARGET_DIR=/opt/cargo_target" >> $GITHUB_ENV

      - name: Cargo Check
        run: cargo check --all

  cargo-test:
    name: Cargo Test
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential pkg-config libclang-dev libssl-dev
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          toolchain: stable
          override: false
      - name: Cargo Tests
        env:
          RUST_LOG: info
        run: cargo t --release
