name: Rust checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-format-and-lint:
    name: Check & Lint
    runs-on: selfhosted-heavy
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup update stable
          rustup default stable
          rustup component add rustfmt clippy

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Lint with clippy
        run: cargo clippy -- -D warnings

  cargo-check:
    name: Cargo Check
    runs-on: selfhosted-heavy
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup update stable
          rustup default stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Check
        run: cargo check --all
